import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[scrolling]
history = 20000
multiplier = 3

[shell]
args = ["-l"]
program = "/opt/homebrew/bin/fish"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.96
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 10
y = 5
