#!/usr/bin/env bash

# Install brew
if command -p brew >/dev/null 2>&1; then
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
export PATH=/opt/homebrew/bin:$PATH
fi

brew bundle

# Run install scripts in dotfiles directories
echo "Running install scripts..."
for file in ~/.dotfiles/*/install; do
    echo "Running $file..."
    bash "$file"
done

$(brew --prefix)/opt/fzf/install --all

# Setup GPG
mkdir -p ~/.gnupg
echo "pinentry-program $(brew --prefix)/bin/pinentry-mac" > ~/.gnupg/gpg-agent.conf
echo 'use-agent' > ~/.gnupg/gpg.conf
fish -C 'source ~/.config/fish/config.fish'
chmod 700 ~/.gnupg
killall gpg-agent
