#!/usr/bin/env bash

rm -rf ~/.config/tmux
ln -s $(pwd)/tmux ~/.config/tmux

if [ ! -d "~/.config/tmux/plugins/tpm" ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
fi
