#!/usr/bin/env bash

rm -rf ~/.config/fish
ln -s $(pwd)/fish ~/.config/fish

# install fisher
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
