#!/usr/bin/env bash

rm -rf ~/.config/fish
ln -s $(pwd)/fish ~/.config/fish

# install fisher
fish <<'END_FISH'
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher install pure-fish/pure
fisher install patrickf1/fzf.fish
END_FISH
